const config = {
    password: "Philippe50", 
    currentLang: 'nl',
    translations: {
        nl: {
            "welcome": "Welkom bij Philippe 50",
            "enter-code": "Voer de geheime code in om deel te nemen:",
            "login-btn": "Log in",
            "wrong-pwd": "Onjuiste code, probeer het opnieuw.",
            "form-title": "Het verhaal van Philippe",
            "label-name": "Jouw Nickname (voor in de legende):",
            "label-email": "Jouw E-mailadres:",
            "label-band": "Schrijf hier het geheime woord dat je band met Philippe duidt:",
            "band-note": "(Dit is je wachtwoord voor later)",
            "label-personage": "Wie is volgens jou een echte superheld?",
            "label-power": "Wat is de superkracht van Philippe?",
            "label-kryptonite": "Waar kan Philippe nog beter in worden?",
            "label-memory": "Omschrijf je leukste herinnering met Philippe in enkele zinnen:",
            "submit-btn": "Verstuur naar de Legende",
            "view-chapter": "Bekijk jouw hoofdstuk",
            "story-title": "De Legende van Philippe",
            "loading-story": "De nevels trekken op...",
            "lookup-title": "Ontgrendel jouw hoofdstuk",
            "lookup-desc": "Voer je nickname en het geheime woord in.",
            "show-story-btn": "Toon mijn verhaal",
            "back-link": "← Terug naar de start",
            "prologue-title": "Hoofdstuk 1: De Tijdsglitch",
            "prologue-text": "Philippe zat op een ochtend in de veranda rustig van een tasje koffie te genieten, met zijn Spotify-playlist op de achtergrond. Met gesloten ogen genoot hij van de zon op zijn gezicht. De combi video- en dvd-speler rolde met zijn ogen en de oude grammofoonspeler onder de televisie kreunde; alweer die 'moderne' muziek.\n\nPlots kwam er een tijdsglitch langs en de grammofoonspeler schrok op. Door de schok verplaatste de naald op een oude plaat en kwam bovenop een van de ribbels terecht. De speler probeerde de naald terug in de juiste groef te schudden, maar de glitch keerde onverwacht terug en de kamer begon te draaien. Philippe merkte niets van de spiraal van duisternis die het licht wegzoog. De kamer leek om hem heen weg te ebben.\n\nToen hoorde hij de Spotify-muziek niet meer. Langzaam klonken vanuit de verte de tonen van de ABBA-hit 'Fernando'. Vreemd, dacht Philippe, dat stond niet in mijn playlist? Hij opende zijn ogen en zag dat hij nog steeds in de zetel zat, maar de kamer was niet meer zijn huis in Kessel-Lo. Hij herkende de plek, maar toch ook niet. Op tafel lag een krant: de geboorteaankondigingen. Er was een kindje geboren met exact dezelfde naam als hij.\n\nHij sloeg de krant dicht. De voorpagina toonde een artikel over de fusie van gemeenten en de viering van 25 jaar Koning Boudewijn. Toen viel zijn Belgische frank: hij stond in de woonkamer van het huis waar hij de eerste twee jaar van zijn leven had gewoond. De datum op de krant: 14 april 1976 om exact 13:30. 50 jaar terug in de tijd. Hoe geraakt hij terug naar de toekomst?",
            "loader-phrases": [
                "De naald zoekt de juiste groef...",
                "Tijdsglitch stabiliseren...",
                "De saphir glijdt door het verleden...",
                "Herinneringen ophalen...",
                "Euhm, ben je zeker dat het langs hier was...",
                "De legende wordt geschreven...",
                "Pas op, we scheren langs een parallel universum...",
                "De platenwisselaar hapert in de tijd...",
                "Echo's uit de toekomst opgevangen...",
                "De tijdlijn wordt hersteld..."
            ],
            "wait-longer": "Het duurt iets langer... geef de naald even een tik en ververs de pagina over een minuutje."
        },
        fr: {
            "welcome": "Bienvenue chez Philippe 50",
            "enter-code": "Entrez le code secret pour participer :",
            "login-btn": "Se connecter",
            "wrong-pwd": "Code incorrect, réessayez.",
            "form-title": "L'histoire de Philippe",
            "label-name": "Votre Nickname (pour la légende) :",
            "label-email": "Votre E-mail :",
            "label-band": "Écrivez ici le mot secret qui définit votre lien avec Philippe :",
            "band-note": "(Ce sera votre mot de passe plus tard)",
            "label-personage": "À quel personnage des années 80 ressemblez-vous le plus ?",
            "label-power": "Selon vous, en quoi Philippe est-il très doué ?",
            "label-kryptonite": "Selon vous, en quoi Philippe pourrait-il s'améliorer ?",
            "label-memory": "Décrivez votre meilleur souvenir avec Philippe en quelques phrases :",
            "submit-btn": "Envoyer à la Légende",
            "view-chapter": "Consultez votre chapitre",
            "story-title": "La Légende de Philippe",
            "loading-story": "Les brumes se lèvent...",
            "lookup-title": "Débloquez votre chapitre",
            "lookup-desc": "Entrez votre nickname et le mot secret.",
            "show-story-btn": "Afficher mon histoire",
            "back-link": "← Retour au début",
            "prologue-title": "Chapitre 1 : Le Glitch Temporel",
            "prologue-text": "Philippe était assis dans sa véranda un matin, savourant tranquillement une tasse de café avec sa playlist Spotify en fond sonore. Les yeux fermés, il profitait du soleil sur son visage. Le combiné lecteur vidéo et DVD leva les yeux au ciel et le vieux gramophone sous le téléviseur grogna ; encore cette musique 'moderne'.\n\nSoudain, une faille temporelle passa par là et le gramophone sursauta. Sous le choc, le saphir se déplaça sur un vieux disque et atterrit sur l'un des sillons. Le gramophone tenta de remettre l'aiguille dans la bonne rainure, mais la faille revint de manière inattendue et la pièce commença soudainement à tourner. Toujours installé dans son fauteuil les yeux clos, Philippe ne remarqua rien de la spirale de ténèbres qui aspirait la lumière. La pièce sembla s'effacer tout autour de lui.\n\nPhilippe n'entendait plus la musique de Spotify, mais les notes du célèbre tube d'ABBA, 'Fernando', résonnaient lentement au loin. Étrange, pensa Philippe, ce n'était pas dans ma playlist. Il ouvrit les yeux et vit qu'il était toujours assis dans son fauteuil. Mais la pièce n'était plus celle de sa maison à Kessel-Lo. Il reconnaissait l'endroit, et pourtant, quelque chose clochait. Sur la table, un journal était ouvert aux annonces de naissance : un enfant était né avec le même nom que lui.\n\nIl referma le journal et vit la une : un article sur les fusions de communes et les festivités pour les 25 ans de règne du roi Baudouin. C'est alors que le 'franc belge' tomba. Philippe se trouvait dans le salon de la maison de ses deux premières années. La date sur le journal : le 14 avril 1976 à 13h30 précises. Cinquante ans en arrière. Comment allait-il retourner vers le futur ?",
            "loader-phrases": [
                "Le saphir cherche le bon sillon...",
                "Stabilisation du glitch temporel...",
                "Le saphir glisse à travers le passé...",
                "Récupération des souvenirs...",
                "Euh, vous êtes sûr que c'était par ici... ?",
                "La légende s'écrit...",
                "Attention, on frôle un univers parallèle...",
                "Le changeur de disques bégaye dans le temps...",
                "Échos du futur interceptés...",
                "La chronologie est en cours de restauration..."
            ],
            "wait-longer": "C'est un peu long... donnez un petit coup au saphir et rafraîchissez la page dans une minute."
        }
    }
};
